from collections.abc import Iterable, Iterator, Mapping
from typing import Any

POLODB_CORE_VERSION: str

class PoloDBError(Exception): ...

class ObjectId:
    def __init__(self, value: str | None = None) -> None: ...
    @property
    def hex(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class _Collection:
    @property
    def name(self) -> str: ...
    def insert_one(self, document: Mapping[str, Any]) -> dict[str, Any]: ...
    def insert_many(self, documents: Iterable[Mapping[str, Any]]) -> dict[int, Any]: ...
    def find_one(self, filter: Mapping[str, Any] | None = None) -> dict[str, Any] | None: ...
    def find(
        self,
        filter: Mapping[str, Any] | None = None,
        *,
        skip: int = 0,
        limit: int = 0,
        sort: Mapping[str, Any] | None = None,
    ) -> _Cursor: ...
    def update_one(
        self,
        filter: Mapping[str, Any],
        update: Mapping[str, Any],
        *,
        upsert: bool = False,
    ) -> dict[str, int]: ...
    def update_many(
        self,
        filter: Mapping[str, Any],
        update: Mapping[str, Any],
        *,
        upsert: bool = False,
    ) -> dict[str, int]: ...
    def delete_one(self, filter: Mapping[str, Any] | None = None) -> dict[str, int]: ...
    def delete_many(self, filter: Mapping[str, Any] | None = None) -> dict[str, int]: ...
    def count_documents(self) -> int: ...
    def aggregate(self, pipeline: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]: ...
    def create_index(
        self,
        keys: Mapping[str, Any],
        *,
        name: str | None = None,
        unique: bool = False,
    ) -> str: ...
    def drop_index(self, name: str) -> None: ...
    def drop(self) -> None: ...

class _Cursor(Iterator[dict[str, Any]]):
    def __iter__(self) -> _Cursor: ...
    def __next__(self) -> dict[str, Any]: ...

class _Transaction:
    @property
    def active(self) -> bool: ...
    def collection(self, name: str) -> _Collection: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

class _Database:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open_path(path: str) -> _Database: ...
    def create_collection(self, name: str) -> None: ...
    def collection(self, name: str) -> _Collection: ...
    def drop_collection(self, name: str) -> None: ...
    def list_collection_names(self) -> list[str]: ...
    def start_transaction(self) -> _Transaction: ...
    def metrics(self) -> dict[str, int]: ...
    def enable_metrics(self) -> None: ...
    @staticmethod
    def set_log(enabled: bool) -> None: ...
