[package]
name = "polodb-python"
version = "0.2.0"
edition = "2024"
description = "Python bindings for PoloDB"
license = "Apache-2.0"

repository = "https://github.com/PoloDB/polodb-python"
homepage = "https://github.com/PoloDB/polodb-python"
documentation = "https://github.com/PoloDB/polodb-python/blob/main/README.md"
exclude = [".venv/", "data/", "dist/", "inspect.sh", "target/"]

[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies]
polodb_core = "5.3.0"
pyo3 = { version = "0.29.2", features = ["abi3-py310", "extension-module"] }

[profile.release]
lto = "thin"
strip = "symbols"

[profile.dist-release]
inherits = "release"
codegen-units = 1
debug = false
lto = "fat"
strip = "symbols"
